### PR TITLE
fix: set default namespace for apis from config

### LINKED ISSUE #1535: Cannot access API without namespace query parameter
Whilst running FF locally, I created a new API using the root level `/apis` call and got a URL for the Swagger UI at `http://127.0.0.1:5001/api/v1/apis/multi-simple-storage/api` but it cannot be found.

Instead if I go to `http://127.0.0.1:5001/api/v1/namespaces/default/apis/multi-simple-storage/api/` then I can access it. So it seems that there has been a regression for the default namespace..

### PR DESCRIPTION
**Pull request by EnriqueL8**
Fixes #1535

### CODE REVIEW

**Review by peterbroadhurst — CHANGES_REQUESTED** [review]
We've made a decision for a long time now, that we never make calls to the config on the critical path runtime.
I think `getBaseURL` is called beyond construction of the route at runtime.

Thus the default namespace needs to be locked in during the initialization of the component, and stored into a variable. Like `dynamicPublicURLHeader` above

**Comment by EnriqueL8** [comment]
aah okay makes sense - let me do that at initialisation time

**Comment by EnriqueL8** [comment]
@peterbroadhurst ready for re-review

**Review by peterbroadhurst — APPROVED** [review]
Thanks for the update 👍

**Pull request merged**
