### PR TITLE
fix-1297

### LINKED ISSUE #1297: Intermittent test failure with TestContractMigration and FF10277
Occurred in https://github.com/hyperledger/firefly/pull/1296 run https://github.com/hyperledger/firefly/actions/runs/4871762457/jobs/8689186525?pr=1296

[logs 17.txt](https://github.com/hyperledger/firefly/files/11384529/logs.17.txt)

```
{"name":"test_1683116741440968188","members":[{"identity":"org_9571df"},{"identity":"org_11bbf0"}]}}
    restclient.go:116: 2023-05-03T12:26:00.712068565Z: <== 500
    restclient.go:118: <!! {"error":"FF10277: Identity could not be resolved via lookup string 'org_11bbf0'"}
    restclient.go:119: Headers: map[Content-Length:[83] Content-Type:[application/json] Date:[Wed, 03 May 2023 12:26:00 GMT] Vary:[Origin]]
    restclient.go:499: Sent private message  to [{Identity:org_9571df Node:} {Identity:org_11bbf0 Node:}]
    contract_migration.go:180: 
        	Error Trace:	/home/runner/work/firefly/firefly/test/e2e/runners/contract_migration.go:180
        	            				/home/runner/work/firefly/firefly/test/e2e/runners/contract_migration.go:51
        	Error:      	Not equal: 
        	            	expected: 202
        	            	actual  : 500
        	Test:       	TestEthereumMultipartyE2ESuite/TestContractMigration
```

### PR DESCRIPTION
**Pull request by peterbroadhurst**
Fixes #1297

### CODE REVIEW

**Comment by awrichar** [comment]
Is it possible to wait for identity confirmed events instead of polling?

**Comment by nguyer** [comment]
I'm trying to go through and clean up stale PR's. @awrichar @peterbroadhurst Do we want to look at waiting for events instead of polling, or merge as-is? Or is this still needed?

**Comment by peterbroadhurst** [comment]
> Is it possible to wait for identity confirmed events instead of polling?

Looking into this

**Comment by peterbroadhurst** [comment]
ok - PR updated with that - sorry for the delay

**Review by nguyer — APPROVED** [review]

**Pull request merged**
