### PR TITLE
Fix docs links

### PR DESCRIPTION
**Pull request by alex-semenyuk**

### CODE REVIEW

**Comment by EnriqueL8** [comment]
Thanks for the PR! Just fixing the pipeline as part of another fix to the FireFly CLI and then checks should pass

**Comment by EnriqueL8** [comment]
@alex-semenyuk Do you mind updating this with main?

**Comment by alex-semenyuk** [comment]
Thanks, done

**Review by EnriqueL8 — APPROVED** [review]
LGTM

**Pull request merged**
