### PR TITLE
Switch from https to ffdx

### PR DESCRIPTION
**Pull request by gabriel-indik**
Signed-off-by: Gabriel Indik <gabriel.indik@kaleido.io>

### CODE REVIEW

**Comment by gabriel-indik** [comment]
Important: https://github.com/hyperledger/firefly-cli/pull/156 should be merged before this change.

**Review by peterbroadhurst — CHANGES_REQUESTED** [review]
The fact the E2E is failing without https://github.com/hyperledger/firefly-cli/pull/156 merging might mean we need a tweak to the migration code in FireFly:

https://github.com/hyperledger/firefly/blob/00fda51127887df1ca783567f334d8daa0244ebd/internal/dataexchange/dxfactory/factory.go#L32-L42

**Comment by gabriel-indik** [comment]
Closing based on the observations in https://github.com/hyperledger/firefly-cli/pull/156#issuecomment-1063163217

**Comment by peterbroadhurst** [comment]
I do believe we need to fix this default @gabriel-indik, so I've done some work to fix the migration to:

1. Cover the case of `https.url` being set, with `ffdx.url` _not_ being set
2. Avoid initializing the prefix on the default paths, so that things like `ff config` do not show the outdated prefix

**Pull request merged**
