### PR TITLE
Fix unique indexes for transfers/approvals to be per-namespace

### PR DESCRIPTION
**Pull request by awrichar**

### CODE REVIEW

**Review by hfuss — COMMENTED** [review]
Looks good to me, will defer to @nguyer and @peterbroadhurst

**Comment by peterbroadhurst** [comment]
Looking at the failures. First failure I looked at is a timeout here:
https://github.com/hyperledger/firefly/blob/ab53a43047f49a4456e7c777d326919cb0c17041/test/e2e/multiparty/tokens.go#L350

From this build: https://github.com/hyperledger/firefly/actions/runs/4885259952/jobs/8719162550

```
goroutine 186 [chan receive, 9 minutes]:
github.com/hyperledger/firefly/test/e2e.WaitForEvent(0xc0001569c0, 0xc0004950e8?, {0xabb667, 0x18}, 0x0)
	/home/runner/work/firefly/firefly/test/e2e/e2e.go:136 +0xa5
github.com/hyperledger/firefly/test/e2e/multiparty.(*TokensTestSuite).TestE2ENonFungibleTokensSync(0xc0000b8960)
	/home/runner/work/firefly/firefly/test/e2e/multiparty/tokens.go:350 +0x1e5c
reflect.Value.call({0xc0000213e0?, 0xc000010270?, 0x40383047434c66?}, {0xaacf79, 0x4}, {0xc000495e70, 0x1, 0x3?})
	/opt/hostedtoolcache/go/1.18.10/x64/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xc0000213e0?, 0xc000010270?, 0xc0000b8960?}, {0xc000495e70, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.18.10/x64/src/reflect/value.go:339 +0xbf
github.com/stretchr/testify/suite.Run.func1(0xc0001569c0)
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.1/suite/suite.go:175 +0x4b6
testing.tRunner(0xc0001569c0, 0xc0001aca20)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f
``

**Comment by peterbroadhurst** [comment]
```
[34mfirefly_core_0_1  |[0m [2023-05-04T17:13:18.438Z] ERROR SQL insert failed: UNIQUE constraint failed: tokenapproval.namespace, tokenapproval.pool_id, tokenapproval.subject sql=[ INSERT INTO tokenapproval (local_id,protocol_id,subject,active,key,operator_key,pool_id,connector,namespace,approved,info,tx_type,tx_id,blockchain_event,created,message_id,message_hash) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ]: UNIQUE constraint failed: tokenapproval.namespace, tokenapproval.pool_id, tokenapproval.subject dbtx=GW0j2N2E ns=default pid=1 role=event-manager
[34mfirefly_core_0_1  |[0m [2023-05-04T17:13:18.438Z] ERROR Failed to record token approval '1': FF00177: Database insert failed: UNIQUE constraint failed: tokenapproval.namespace, tokenapproval.pool_id, tokenapproval.subject dbtx=GW0j2N2E ns=default pid=1 role=event-manager
[34mfirefly_core_0_1  |[0m [2023-05-04T17:13:18.438Z]  WARN SQL! transaction rollback dbtx=GW0j2N2E ns=default pid=1 role=event-manager
[34mfirefly_core_0_1  |[0m [2023-05-04T17:13:18.438Z] ERROR persist token approval attempt 26: FF00177: Database insert failed: UNIQUE constraint failed: tokenapproval.namespace, tokenapproval.pool_id, tokenapproval.subject ns=default pid=1 role=event-manager

```

**Comment by awrichar** [comment]
I got over-aggressive about "fixing" indexes. One did not need to be fixed.

**Pull request merged**
