### PR TITLE
Add Performance Testing Details to README

### PR DESCRIPTION
**Pull request by eberger727**
Adding performance testing details to README

### CODE REVIEW

**Review by peterbroadhurst — CHANGES_REQUESTED** [review]
Hi @eberger727 - I wonder if it makes sense to make the FireFly readme section just link to the Performance CLI (like it does for other components), and for the architecture for the performance CLI to go into the README of that tool?

**Comment by peterbroadhurst** [comment]
e.g. just update this section: https://github.com/hyperledger/firefly#git-repositories

**Review by peterbroadhurst — APPROVED** [review]
👍

**Comment by nguyer** [comment]
I'm going to close and re-open this to try to get the build to pass now that we fixed the linting issue.

**Pull request merged**
