### PR TITLE
Add additional test suite for running E2E tests without tokenTestSuite against specific Firefly namespace

### PR DESCRIPTION
**Pull request by calbritt**
Can call test suite directly to run without token test suite.

### CODE REVIEW

**Review by awrichar — CHANGES_REQUESTED** [review]
I'm slightly wary of having a suite that reads a config file to decide which tests it will or will not run. Feels like it's better to explicitly say which tests need to run, or you'd have to carefully inspect the output to ensure a test wasn't unintentionally skipped.

Can you give some background on the motivation for this?

**Comment by calbritt** [comment]
> I'm slightly wary of having a suite that reads a config file to decide which tests it will or will not run. Feels like it's better to explicitly say which tests need to run, or you'd have to carefully inspect the output to ensure a test wasn't unintentionally skipped.
> 
> Can you give some background on the motivation for this?

For firefly stacks that don't have a token connector running we want to be able to still complete a successful E2E run without the tokens test failing.

**Comment by awrichar** [comment]
OK - would it make sense to have a different top-level suite for that?

**Comment by calbritt** [comment]
I will change existing '*E2ESuite* files to use `Runner` as new suffix to indicate these are running a compilation of test suites. As part of that change I will also add something like a `NoTokenConnectorRunner` file to contain all Ethereum E2E tests not including TokensTestSuite instead of skipping the tests.

**Pull request closed without merging**
