### PR TITLE
Validate message topics/tag before sending

### PR DESCRIPTION
**Pull request by awrichar**
Currently these fields are verified only by the receiver, which can lead to
sending a bad message that is rejected on the other end.

### CODE REVIEW

**Comment by awrichar** [comment]
Looks like on Fabric, we generate an invalid topic name for org broadcasts. Not sure why it was working before - perhaps we're not doing the receiver-side validation of messages when dealing with org broadcasts? Seems like that should be in effect for all messages, including system definitions.

**Comment by awrichar** [comment]
After further investigation, there are actually a few layers of problems here.
1. We are [ignoring message validation errors](https://github.com/hyperledger/firefly/blob/7065837c64321b70b755556954bb574071df8899/internal/events/persist_batch.go#L200) in many cases and persisting received messages that failed to validate
2. We are generating topic names for Fabric root org broadcasts which violate the 64-char max length (and could therefore overflow db columns)
3. Validation of FF names was [extended](https://github.com/hyperledger/firefly/pull/262) to disallow UUIDs as names - but there are some cases (such as topic) where a UUID is acceptable, and other cases (such as token pools) where a UUID would cause confusion in a get-by-name-or-id scenario
4. Topics and tags are not being validated by the sender before sending a message (ie the original issue noted in this PR)

**Comment by awrichar** [comment]
Pushed additional fixes for the issues noted above. See each commit message for more details.

**Review by peterbroadhurst — APPROVED** [review]
Noting this contains a material change, that organizations are now all published on a common `ff_organizations` topic.

**Pull request merged**
