### PR TITLE
Postgres concurrency:true

### PR DESCRIPTION
**Pull request by peterbroadhurst**
While doing some performance work, I detected the background writers for operations introduce to significantly reduce load on the database were disabled with Postgres.

```
[2023-06-13T21:59:00.193Z]  INFO Database plugin not configured for concurrency. Batched message writing disabled ns=dtcc3 pid=1
[2023-06-13T21:59:00.194Z]  INFO Database plugin not configured for concurrency. Batched operation updates disabled ns=dtcc3 pid=1
```

This has previously been handled with a check on the connection limit that updates this value:
https://github.com/hyperledger/firefly/blob/ea38e01833f982b369e7033371e94d63a7331b92/internal/database/sqlcommon/sqlcommon.go#L82-L84

However, that has now moved to `firefly-common` and `capabilities` is not passed down.

https://github.com/hyperledger/firefly-common/blob/1f12860e6b44af18f024ea0cadef69b22d00bc73/pkg/dbsql/database.go#L87-L98

### CODE REVIEW

**Comment by peterbroadhurst** [comment]
E2E test failure shows:
```
2023-06-13T22:41:24.5934807Z     e2e.go:253: Waiting on operations:
2023-06-13T22:41:24.5935745Z         Operation '97ce5f77-cd6d-439a-8319-48767c91d9b9' (blockchain_invoke) on 'http://127.0.0.1:5000/api/v1' status=Failed
2023-06-13T22:41:26.5951007Z     e2e.go:257: 
2023-06-13T22:41:26.5956641Z         	Error Trace:	/home/runner/work/firefly/firefly/test/e2e/runners/e2e.go:257
2023-06-13T22:41:26.5960514Z         	            				/home/runner/work/firefly/firefly/test/e2e/runners/ethereum_contracts.go:142
2023-06-13T22:41:26.5970404Z         	            				/home/runner/work/firefly/firefly/test/e2e/runners/suite.go:153
2023-06-13T22:41:26.5978490Z         	            				/home/runner/work/firefly/firefly/test/e2e/runners/panic.go:522
2023-06-13T22:41:26.5983010Z         	            				/home/runner/work/firefly/firefly/test/e2e/runners/testing.go:871
2023-06-13T22:41:26.5983995Z         	            				/home/runner/work/firefly/firefly/test/e2e/runners/restclient.go:835
2023-06-13T22:41:26.5984998Z         	            				/home/runner/work/firefly/firefly/test/e2e/runners/ethereum_contracts.go:235
2023-06-13T22:41:26.6038190Z         	Error:      	Operation '97ce5f77-cd6d-439a-8319-48767c91d9b9' (blockchain_invoke) on 'http://127.0.0.1:5000/api/v1' status=Failed
2023-06-13T22:41:26.6039050Z         	Test:       	TestEthereumMultipartyE2ESuite/TestFFIInvokeMethod
2023-06-13T22:41:26.6039683Z Websocket 127.0.0.1:5000 closing, error: read tcp 127.0.0.1:60430->127.0.0.1:5000: use of closed network connection
2023-06-13T22:41:26.6040104Z     common.go:192: WebSockets closed
```

**Review by awrichar — COMMENTED** [review]
Looks good but the test failure probably needs triage

**Comment by nguyer** [comment]
E2E is currently failing because FireFly Core is no longer getting a idempotency key conflict on this token approval, because the DB now has concurrency. This uncovers the fact that the token connector always returns a 500 for any kind of error response from the blockchain connector, which is why FireFly now sends a 500 back to the client instead of a 409. I think the "right" fix here is to enable the token connector to pass the 409 all the way back through.

```
    restclient.go:701: 
        	Error Trace:	/home/runner/work/firefly/firefly/test/e2e/runners/restclient.go:701
        	            				/home/runner/work/firefly/firefly/test/e2e/runners/tokens.go:97
        	Error:      	Not equal: 
        	            	expected: 409
        	            	actual  : 500
        	Test:       	TestEthereumMultipartyE2ESuite/TestE2EFungibleTokensAsync
        	Messages:   	POST /namespaces/default/tokens/approvals [500]: {"error":"FF10274: Error from tokens service: Internal Server Error: FF21065: ID 
```

**Comment by nguyer** [comment]
I did some more investigation on the E2E failure here and was able to reproduce it locally. Here is what I found.

When we get two token transfer requests back to back, we hit this block of code in `token_transfer.go`. When DB concurrency is enabled, some things happen on background threads, so we can end up in a state where the operation for this transaction is still in `Initialized`. That makes this code think that it needs to re-submit the same operation for a pre-existing transaction, so we end up sending the same request to EVMConnect twice.

https://github.com/kaleido-io/firefly/blob/e405f9af092fb925e39757aedfdc739d702c3bee/internal/assets/token_transfer.go#L193-L207
```go
	if err != nil {
		// Check if we've clashed on idempotency key. There might be operations still in "Initialized" state that need
		// submitting to their handlers. Note that we'll return the result of resubmitting the operation, not a 409 Conflict error
		if idemErr, ok := err.(*sqlcommon.IdempotencyError); ok {
			operation, resubmitErr := s.mgr.operations.ResubmitOperations(ctx, idemErr.ExistingTXID)
			if resubmitErr != nil {
				// Error doing resubmit, return the new error
				err = resubmitErr
			} else if operation != nil {
				// We successfully resubmitted an initialized operation, return 2xx not 409
				return true, nil
			}
		}
		return true, err
	}
```

Here is a log of this happening in FireFly Core:
```
[2023-06-20T19:31:27.239Z]  INFO Executing token_transfer operation 67bc0c54-30ed-469a-88c7-fe41937cf074 via handler AssetManager httpreq=Q2SD2WNe pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.239Z] DEBUG Notifying batch manager of rewind to 56 ns=default pid=1 role=batchmgr
[2023-06-20T19:31:27.239Z] DEBUG ==> POST http://tokens_1_0:3000/api/v1/transfer breq=1esauZiT pid=1 proto=fftokens
[2023-06-20T19:31:27.239Z] DEBUG SQL-> query messages ns=default pid=1 role=batchmgr
[2023-06-20T19:31:27.239Z] DEBUG SQL<- query messages ns=default pid=1 role=batchmgr
[2023-06-20T19:31:27.239Z] DEBUG Read 0 records from offset 49. filtered=0 fullPage=false ns=default pid=1 role=batchmgr
[2023-06-20T19:31:27.283Z] DEBUG <== POST http://tokens_1_0:3000/api/v1/transfer [202] (44.65ms) breq=1esauZiT pid=1 proto=fftokens
[2023-06-20T19:31:27.284Z] DEBUG fftokens updating operation default:67bc0c54-30ed-469a-88c7-fe41937cf074 status=Pending ns=default pid=1
[2023-06-20T19:31:27.284Z] DEBUG Submitting operation update id=67bc0c54-30ed-469a-88c7-fe41937cf074 status=Pending blockchainTX= worker=opu_001 ns=default pid=1
[2023-06-20T19:31:27.284Z]  INFO <-- POST /api/v1/namespaces/default/tokens/transfers [202] (60.64ms) httpreq=Q2SD2WNe pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.284Z]  INFO Received operation update: status=Succeeded request=default:67bc0c54-30ed-469a-88c7-fe41937cf074 tx=0xf070bb131308289bd02f27f40c2213343cbf66b3af1360b4e987e5a118147e2c message= pid=1 proto=ethereum role=event-loop
[2023-06-20T19:31:27.284Z] DEBUG ethereum updating operation default:67bc0c54-30ed-469a-88c7-fe41937cf074 status=Succeeded ns=default pid=1
[2023-06-20T19:31:27.284Z] DEBUG Submitting operation update id=67bc0c54-30ed-469a-88c7-fe41937cf074 status=Succeeded blockchainTX=0xf070bb131308289bd02f27f40c2213343cbf66b3af1360b4e987e5a118147e2c worker=opu_001 ns=default pid=1
[2023-06-20T19:31:27.285Z]  INFO --> POST /api/v1/namespaces/default/tokens/transfers httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.285Z] DEBUG SQL-> begin dbtx=MQvcRnj2 httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.285Z] DEBUG SQL<- begin dbtx=MQvcRnj2 httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.285Z] DEBUG SQL-> insert transactions dbtx=MQvcRnj2 httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.286Z] DEBUG SQL insert failed (conflictEmptyRequested=true): FF00185: Failed to retrieve sequence for insert row 1 (could mean duplicate insert) sql=[ INSERT INTO transactions (id,ttype,namespace,created,idempotency_key,blockchain_ids) VALUES ($1,$2,$3,$4,$5,$6)  ON CONFLICT DO NOTHING RETURNING seq ]: FF00185: Failed to retrieve sequence for insert row 1 (could mean duplicate insert) dbtx=MQvcRnj2 httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.286Z] DEBUG SQL-> query transactions dbtx=MQvcRnj2 httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.286Z] DEBUG SQL<- query transactions dbtx=MQvcRnj2 httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.286Z]  WARN SQL! transaction rollback dbtx=MQvcRnj2 httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.286Z] DEBUG SQL-> query operations httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.286Z] DEBUG SQL<- query operations httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.286Z] DEBUG SQL-> query tokenpool httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.287Z] DEBUG SQL<- query tokenpool httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.287Z]  INFO Executing token_transfer operation 67bc0c54-30ed-469a-88c7-fe41937cf074 via handler AssetManager httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.287Z] DEBUG ==> POST http://tokens_1_0:3000/api/v1/transfer breq=XMlyCcob pid=1 proto=fftokens
[2023-06-20T19:31:27.287Z] DEBUG Received receipt event  pid=1 proto=fftokens role=event-loop
[2023-06-20T19:31:27.288Z]  INFO Received operation update: status=Succeeded request=default:67bc0c54-30ed-469a-88c7-fe41937cf074 message= pid=1 proto=fftokens role=event-loop
[2023-06-20T19:31:27.288Z] DEBUG fftokens updating operation default:67bc0c54-30ed-469a-88c7-fe41937cf074 status=Succeeded ns=default pid=1
[2023-06-20T19:31:27.288Z] DEBUG Submitting operation update id=67bc0c54-30ed-469a-88c7-fe41937cf074 status=Succeeded blockchainTX=0xf070bb131308289bd02f27f40c2213343cbf66b3af1360b4e987e5a118147e2c worker=opu_001 ns=default pid=1
[2023-06-20T19:31:27.334Z] DEBUG SQL-> begin dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.334Z] DEBUG SQL<- begin dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.334Z] DEBUG SQL-> update operations dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.335Z] DEBUG SQL<- update operations affected=1 dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.335Z] DEBUG Operation update 'default:67bc0c54-30ed-469a-88c7-fe41937cf074' from 'ethereum' ignored, as it does not match operation source 'fftokens' dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.335Z] DEBUG SQL-> update transactions dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.335Z] DEBUG SQL<- update transactions affected=1 dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.335Z] DEBUG SQL-> update operations dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.335Z] DEBUG SQL<- update operations affected=1 dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.335Z] DEBUG SQL-> commit dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.336Z] DEBUG SQL<- commit dbtx=SHVLAfr_ ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.346Z] ERROR <== POST http://tokens_1_0:3000/api/v1/transfer [500] (59.50ms) breq=XMlyCcob pid=1 proto=fftokens
[2023-06-20T19:31:27.347Z] DEBUG fftokens updating operation default:67bc0c54-30ed-469a-88c7-fe41937cf074 status=Failed error=FF10274: Error from tokens service: Internal Server Error: FF23021: EVM reverted: ERC20: transfer amount exceeds balance ns=default pid=1
[2023-06-20T19:31:27.347Z] DEBUG Submitting operation update id=67bc0c54-30ed-469a-88c7-fe41937cf074 status=Failed blockchainTX= worker=opu_001 ns=default pid=1
[2023-06-20T19:31:27.347Z]  INFO <-- POST /api/v1/namespaces/default/tokens/transfers [500] (61.69ms): FF10274: Error from tokens service: Internal Server Error: FF23021: EVM reverted: ERC20: transfer amount exceeds balance httpreq=O5UjIInl pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.350Z]  INFO --> GET /api/v1/namespaces/default/operations httpreq=8FCPzHWR pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.350Z] DEBUG Query: created=%3E1687289481924731000 httpreq=8FCPzHWR pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.350Z] DEBUG SQL-> query operations httpreq=8FCPzHWR pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.351Z] DEBUG SQL<- query operations httpreq=8FCPzHWR pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.351Z]  INFO <-- GET /api/v1/namespaces/default/operations [200] (0.51ms) httpreq=8FCPzHWR pid=1 req=rEkg7vGn
[2023-06-20T19:31:27.397Z] DEBUG SQL-> begin dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.397Z] DEBUG SQL<- begin dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.397Z] DEBUG SQL-> update operations dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.398Z] DEBUG SQL<- update operations affected=1 dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.398Z] DEBUG SQL-> lock default dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.398Z] DEBUG SQL<- lock default dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.398Z] DEBUG SQL-> insert events dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.398Z] DEBUG SQL<- insert events sequences=[111] dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.398Z] DEBUG SQL-> commit dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.400Z] DEBUG SQL<- commit dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
[2023-06-20T19:31:27.400Z]  INFO Emitted token_transfer_op_failed event 423dfc34-39ca-461e-86fc-c0d716af0412 for default:67bc0c54-30ed-469a-88c7-fe41937cf074 (correlator=8c7e9fbc-2df3-4f21-ae4c-a721396c9b5d,topic=7857f478-1e4f-4b72-a323-ee54a03dff00) dbtx=tG_itAu1 ns=default opupdater=opu_001 pid=1
```

The strange part is that EVMConnect does not fail with a 409 due to the operation ID (and therefore the EVMConnect Request ID) being the same. Instead, it fails on the gas estimate and determines that it _will not be able to_ successfully run this transaction (due to not having sufficient balance), so it returns 500. This happens because it never reaches the point of attempting to put the transaction into its transaction queue where it would have found the Request ID conflict and returned a 409.

**Comment by peterbroadhurst** [comment]
The 409 pre-check needed to allow EVMConnect to return a `409` _before_ doing Gas Estimation, has been added in this commit https://github.com/hyperledger/firefly-transaction-manager/pull/85/commits/346cd5c72fd574d98624bc8fb41a9a8da7b0f74a of FFTM PR https://github.com/hyperledger/firefly-transaction-manager/pull/85

**Pull request merged**
